---
title: "Untitled"
output: html_document
date: "2025-04-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
```

```{r}
library(tidyverse)
targets::tar_load_everything()




theme_kp <- function() {  # this for all the elements common across plots
  theme_bw() %+replace%
    theme(legend.position = "top",
          legend.key=element_blank(),
          legend.title = element_text(size = 14, hjust = 0),
          legend.text = element_text(size = 14),
          legend.key.size = unit(1.5, 'lines'),
          legend.background = element_rect(colour = NA),
          panel.border = element_rect(color="black",linewidth=1, fill = NA),
          
          plot.title = element_text(hjust = 0, size = 14),
          axis.text = element_text(size = 14, color = "black"),
          axis.title = element_text(size = 14, face = "bold", color = "black"),
          
          # formatting for facets
          panel.background = element_blank(),
          strip.background = element_rect(colour="white", fill="white"), #facet formatting
          panel.grid = element_blank(),
          panel.spacing.x = unit(1, "lines"), #facet spacing for x axis
          panel.spacing.y = unit(1.5, "lines"), #facet spacing for x axis
          strip.text.x = element_text(size=14, face="bold"), #facet labels
          strip.text.y = element_text(size=14, face="bold", angle = 270) #facet labels
    )
}
theme_set(theme_kp())

```


# XCT

## PNM

```{r pnm_radius}
  
pnm_clean2 = 
  xct_pnm_processed %>% 
  mutate(water_treatment = paste(water_treatment, "water"),
         water_treatment = factor(water_treatment, levels = c("low water", "high water")))



pnm_clean2 %>% 
    filter(core_name %in% c("FOR_01", "FOR_05")) %>% 
    filter(grepl("T", timepoint)) %>% 
    ggplot(aes(x = EqRadius, color = timepoint, group = timepoint)) +
    geom_density(linewidth = 1, show.legend = F)+
    facet_wrap(~water_treatment)+
    xlim(0, 2.5)+
    scale_color_manual(values = c("black", "lightblue", "#dd4124", "blue", "darkred", "darkblue", "orange"),
                       breaks = c("T0", "F1", "T1", "F2", "T2", "F3", "T3"))+
  labs(x = "radius (mm)")+
  theme(panel.grid = element_blank())


pnm_clean2 %>% 
  filter(core_name %in% c("FOR_01", "FOR_05")) %>% 
  #   filter(grepl("T", timepoint)) %>% 
  ggplot(aes(x = EqRadius, color = timepoint, group = timepoint)) +
  geom_density(linewidth = 1, show.legend = F)+
  facet_wrap(~water_treatment)+
  xlim(0, 2.5)+
  scale_color_manual(values = c("black", "lightblue", "#dd4124", "blue", "darkred", "darkblue", "orange"),
                     breaks = c("T0", "F1", "T1", "F2", "T2", "F3", "T3"))+
  labs(x = "radius (mm)")+
  theme(panel.grid = element_blank())
```

```{r pnm_coordination_raincloud}

pnm_clean2 %>% 
  filter(core_name %in% c("FOR_01", "FOR_04")) %>% 
  filter(grepl("T", timepoint)) %>% 
  ggplot(aes(x = timepoint, y = Coordination.Number, color = timepoint, group = timepoint, fill = timepoint)) +
  ggdist::stat_halfeye(#aes(fill = Incubation), 
    size = 1, alpha = 0.5,
    position = position_nudge(x = 0.2), width = 0.5)+
  geom_jitter(width = 0.15, size = 0.8)+
  scale_color_manual(values = c("black", "lightblue", "#dd4124", "blue", "darkred", "darkblue", "orange"),
                     breaks = c("T0", "F1", "T1", "F2", "T2", "F3", "T3"))+
  scale_fill_manual(values = c("black", "lightblue", "#dd4124", "blue", "darkred", "darkblue", "orange"),
                    breaks = c("T0", "F1", "T1", "F2", "T2", "F3", "T3"))+
  labs(x = "", 
       y = "Pore Coordination Number")+
  facet_wrap(~water_treatment, nrow = 2)+
  theme(panel.grid = element_blank(),
        legend.position = "none")








  # '#00496f', '#0f85a0', '#edd746', '#ed8b00', '#dd4124'

```


```{r pnm_coordination_map}
# coordinations

xct_pnm_processed %>% filter(core_name == "FOR_01" & 
                               Coordination.Number == 0  & 
                               grepl("T", timepoint) &
                               timepoint %in% c("T0", "T3")
                             ) %>% 
  ggplot(aes(x = X.Coord, y = Z.Coord, size = EqRadius))+
  geom_point(color = "black")+
  geom_point(data = pnm_clean2 %>% filter(core_name == "FOR_01" & 
                               Coordination.Number > 20  & 
                               grepl("T", timepoint) &
                               timepoint %in% c("T0", "T3")
                             ),
             color = '#ed8b00')+
  facet_wrap(~timepoint, nrow = 1)+
  scale_size(range = c(2, 6))+
  theme(legend.position = "none",
        axis.text = element_blank(),
        axis.title = element_blank())



xct_pnm_processed %>% filter(core_name == "FOR_04" & 
                               Coordination.Number == 0  & 
                               grepl("T", timepoint) &
                               timepoint %in% c("T0", "T3")
                             ) %>% 
  ggplot(aes(x = X.Coord, y = Z.Coord, size = EqRadius))+
  geom_point(color = "black")+
  geom_point(data = pnm_clean2 %>% filter(core_name == "FOR_04" & 
                               Coordination.Number > 20  & 
                               grepl("T", timepoint) &
                               timepoint %in% c("T0", "T3")
                             ),
             color = '#ed8b00')+
  facet_wrap(~timepoint, nrow = 1)+
  scale_size(range = c(2, 6))+
  theme(legend.position = "none",
        axis.text = element_blank(),
        axis.title = element_blank())

  


```


```{r pnm_coordination_map_throats}

throats = 
  pnm_clean2 %>% 
  dplyr::select(core_name, water_treatment, timepoint,
                Throat.ID, EqRadius.1, Pore.ID..1, Pore.ID..2)


pores =
  pnm_clean2 %>% 
#  filter(Coordination.Number == 0 | Coordination.Number > 20) %>% 
  dplyr::select(core_name, water_treatment, timepoint,
                Pore.ID, X.Coord, Z.Coord, Coordination.Number)



throats2 = 
  throats %>% 
  left_join(pores, by = c("core_name", "water_treatment", "timepoint", "Pore.ID..1" = "Pore.ID")) %>% 
  rename(x1 = X.Coord, 
         z1 = Z.Coord) %>% 
  left_join(pores, by = c("core_name", "water_treatment", "timepoint", "Pore.ID..2" = "Pore.ID")) %>% 
  rename(x2 = X.Coord, 
         z2 = Z.Coord) %>% 
  filter(Coordination.Number.x == 0 | Coordination.Number.x > 20 | Coordination.Number.y == 0 | Coordination.Number.y > 20)



throats2 %>% 
  filter(core_name == "FOR_04" & 
                               timepoint %in% c("T0", "T3")) %>% 
  ggplot()+
  geom_segment(aes(x = x1, y = z1, xend = x2, yend = z2),
               #color = "#ed8b00", 
               color = "black",
               alpha = 0.3)+
  facet_wrap(~ timepoint)+
  

#  geom_point(data = xct_pnm_processed %>% filter(core_name == "FOR_04" & 
#                               Coordination.Number == 0  & 
#                               grepl("T", timepoint) &
#                               timepoint %in% c("T0", "T3")
#                             ),
#             aes(x = X.Coord, y = Z.Coord, size = EqRadius),
#             color = "black")+
  geom_point(data = pnm_clean2 %>% filter(core_name == "FOR_04" & 
                               Coordination.Number > 20  & 
                               grepl("T", timepoint) &
                               timepoint %in% c("T0", "T3")
                             ),
             aes(x = X.Coord, y = Z.Coord, size = EqRadius),
             color = '#ed8b00')+
 # facet_wrap(~timepoint, nrow = 1)+
  scale_size(range = c(2, 6))+
  theme(legend.position = "none",
        axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank())


throats2 %>% 
  filter(core_name == "FOR_01" & 
                               timepoint %in% c("T0", "T3")) %>% 
  ggplot()+
  geom_segment(aes(x = x1, y = z1, xend = x2, yend = z2),
               #color = "#ed8b00", 
               color = "black",
               alpha = 0.3)+
  facet_wrap(~timepoint)+
  

#  geom_point(data = xct_pnm_processed %>% filter(core_name == "FOR_01" & 
#                               Coordination.Number == 0  & 
#                               grepl("T", timepoint) &
#                               timepoint %in% c("T0", "T3")
#                             ),
#             aes(x = X.Coord, y = Z.Coord, size = EqRadius),
#             color = "black")+
  geom_point(data = pnm_clean2 %>% filter(core_name == "FOR_01" & 
                               Coordination.Number > 20  & 
                               grepl("T", timepoint) &
                               timepoint %in% c("T0", "T3")
                             ),
             aes(x = X.Coord, y = Z.Coord, size = EqRadius),
             color = '#ed8b00')+
 # facet_wrap(~timepoint, nrow = 1)+
  scale_size(range = c(2, 6))+
  theme(legend.position = "none",
        axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank())
  

```



```{r}
throats2 %>% 
  filter(core_name == "FOR_01") %>% 
  ggplot()+
  geom_segment(aes(x = x1, y = z1, xend = x2, yend = z2),
               #color = "#ed8b00", 
               color = "black",
               alpha = 0.2)+
  facet_grid(core_name ~ timepoint)
```




## Summaries

```{r summary_volume}

xct_summary2 = 
  xct_summary_processed %>% 
  mutate(water_treatment = paste(water_treatment, "water"),
         water_treatment = factor(water_treatment, levels = c("low water", "high water")))


  xct_summary2 %>% 
    filter(!is.na(timepoint)) %>% 
    ggplot(aes(x = timepoint, y = total_volume_pores_mm3, color = water_treatment, group = core_name))+
    geom_point(size = 3)+
    geom_line()+
    scale_color_manual(values = (PNWColors::pnw_palette("Bay", 5)))+
      labs(x = "", 
       y = "Pore Volume (mm3)")+
    facet_wrap(~water_treatment)+
      theme(panel.grid = element_blank(),
        legend.position = "none")

  
```

```{r summary_connected}

xct_summary2 %>% 
  filter(!is.na(timepoint)) %>% 
  filter(core_name == "FOR_01") %>% 
  ggplot(aes(x = timepoint, y = connected_pores_percent, color = water_treatment, group = core_name))+
  geom_line(color = "black", linewidth = 1)+
  geom_point(size = 5, color = "white", fill = "black", shape = 21, stroke = 2)+
  ylim(75, 100)+
  facet_wrap(~water_treatment)+
  labs(y = "Connected Pores (%)",
       x = "")+
  theme(legend.position = "none")


xct_summary2 %>% 
  filter(!is.na(timepoint)) %>% 
  filter(core_name == "FOR_04") %>% 
  ggplot(aes(x = timepoint, y = connected_pores_percent, color = water_treatment, group = core_name))+
  geom_line(color = "black", linewidth = 1)+
  geom_point(size = 5, color = "white", fill = "black", shape = 21, stroke = 2)+
  ylim(75, 100)+
  facet_wrap(~water_treatment)+
  labs(y = "Connected Pores (%)",
       x = "")+
  theme(legend.position = "none")



```




# RESPIRATION

```{r licor_ppm}

licor_processed_rates %>% 
  mutate(timepoint = factor(timepoint, levels = c("t0", "ftc1", "ftc2", "ftc3"))) %>% 
  filter(water_treatment != "ambient") %>% 
  filter(!is.na(timepoint)) %>% 
  filter(elapsed_hr < 20) %>% 
  filter(!core_name %in% c("FOR_20", "FOR_21")) %>% 
  ggplot(aes(x = elapsed_hr, y = co2_max_ppm, group = core_name, color = water_treatment))+
  geom_line()+
  facet_grid(water_treatment+core_name ~ timepoint, scales = "free_x")


```

```{r licor_ppm_smooth}

licor_processed_rates %>% 
  mutate(timepoint = factor(timepoint, levels = c("t0", "ftc1", "ftc2", "ftc3"))) %>% 
  filter(water_treatment != "ambient") %>% 
  filter(!is.na(timepoint)) %>% 
  filter(elapsed_hr < 20) %>% 
  # filter(datetime >= ymd_hms("2025-02-18 13:00:00") & datetime <= ymd_hms("2025-02-18 19:00:00")) %>% 
  filter(!core_name %in% c("FOR_10", "FOR_20", "FOR_21")) %>% 
  ggplot(aes(x = elapsed_hr, y = co2_max_ppm, group = core_name, color = water_treatment))+
  geom_line(alpha = 0.5)+
  geom_smooth(se = F, aes(group = water_treatment), linewidth = 2)+
  facet_grid(. ~ timepoint, scales = "free_x")

```

```{r licor_cumulative, fig.height=6, fig.width=8}
licor_cumulative = licor_cumulative %>% 
  mutate(timepoint = toupper(timepoint),
         timepoint = factor(timepoint, levels = c("T0", "FTC1", "FTC2", "FTC3")),
         water_treatment = factor(water_treatment, levels = c("low water", "high water")))


licor_cumulative %>% 
  filter(core_name %in% c("FOR_07", "FOR_08", "FOR_09", "FOR_11", "FOR_12")) %>% 
  group_by(water_treatment, timepoint) %>% 
  dplyr::summarise(mean = mean(co2_umol_cum)) %>% 
  ggplot(aes(x = timepoint, y = mean, fill = (water_treatment)))+
  geom_bar(stat = "identity", width = 0.3, position = position_dodge(width = 0.5), color = "black")+
  scale_fill_manual(values = c( "#CEA07E", "#155CA2"))+
  labs(y = "Cumulative CO2 evolved, μmol",
       fill = "",
       x = "")+
  theme(legend.position = c(0.8, 0.8))


```



# WEOM

```{r}

weoc_processed = 
  weoc_processed %>% 
  mutate(ftc = toupper(ftc),
         ftc = factor(ftc, levels = c("T0", "FTC1", "FTC2", "FTC3")),
         water_treatment = paste(water_treatment, "water"),
         water_treatment = factor(water_treatment, levels = c("low water", "high water")))


  weoc_processed %>% 
    filter(tube_type == "destructive cores") %>% 
    ggplot(aes(x = ftc, y = npoc_ugg, color = water_treatment))+
    geom_point(size = 4)+
    scale_color_manual(values = c( "#CEA07E", "#155CA2"))+
      labs(y = "Water-extractable organic C (μg/g)
           ",
       color = "",
       x = "")

  
#  weoc_processed %>% 
#    filter(tube_type == "destructive cores") %>% 
#    ggplot(aes(x = ftc, y = tn_ugg, color = water_treatment))+
#    geom_point(size = 3)
#  
#  weoc_processed %>% 
#    filter(tube_type == "GHG cores" | ftc == "t0") %>% 
#    ggplot(aes(x = ftc, y = npoc_ugg, color = water_treatment))+
#    geom_point(size = 3)
  

```


```{r}


  
  mbc_processed %>% 
    filter(tube_type == "destructive cores") %>% 
    ggplot(aes(x = ftc, y = mbc_ugg, color = water_treatment))+
    geom_point(size = 3)
  
  mbc_processed %>% 
    filter(tube_type == "destructive cores") %>% 
    ggplot(aes(x = ftc, y = mbn_ugg, color = water_treatment))+
    geom_point(size = 3)
  
  mbc_processed %>% 
    filter(tube_type == "GHG cores" | ftc == "t0") %>% 
    ggplot(aes(x = ftc, y = mbc_ugg, color = water_treatment))+
    geom_point(size = 3)
  
  
```

